spring.application.name=MinE-Comm
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Set max file size for single file upload (e.g., 100MB)
spring.servlet.multipart.max-file-size=100MB
# Set max request size for total upload (e.g., multiple files in a single request)
spring.servlet.multipart.max-request-size=100MB

spring.ai.google.genai.api-key=${GOOGLE_AI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
stability.api.key=${STABILITY_API_KEY}

spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always
spring.ai.google.genai.embedding.api-key=${GOOGLE_AI_EMBEDDING_API_KEY}
spring.ai.google.genai.chat.options.vertex-ai=false
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
# spring.ai.google.genai.embedding.options.output-dimensionality=1536

#spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.main.allow-bean-definition-overriding=true